name: Bazel Build

on:
  push:
    branches:
      - main  # Change to your default branch if different
  pull_request:
    branches:
      - main  # Change to your default branch if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bazelisk
        uses: bazelbuild/setup-bazelisk@v3

      - name: Mount bazel cache  # Optional
        uses: actions/cache@v4
        with:
          path: ~/.cache/bazel
          key: bazel-${{ runner.os }}-${{ hashFiles('**/BUILD', '**/*.bzl') }}

      - name: Build with Bazel
        run: bazel build //...
      - name: test with Bazel
        run: bazel test //...
        
